# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
import numpy as np
np.random.seed(25)
ageArray = np.random.randint(10,25,25)
ageArray


array([14, 24, 20, 23, 16, 17, 22, 12, 23, 18, 22, 14, 19, 23, 14, 15, 11,
       17, 13, 18, 17, 13, 14, 23, 13])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
newarray=np.arange(1,50,2)
print(len(newarray))



25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
newarray1=np.linspace(4,7,27)
print(newarray1)



[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:

np.random.seed(25)
ageArray = np.random.rand(10,25)
ageArray.resize(5,4)
print('before round off'+str(ageArray))
print('after round off'+str(np.round(ageArray,2)))


before round off[[0.87012414 0.58227693 0.27883894 0.18591123]
 [0.41110013 0.11737555 0.68496874 0.43761106]
 [0.55622933 0.36708032 0.40236573 0.1130407 ]
 [0.44703085 0.58544512 0.1619851  0.52071879]
 [0.32605113 0.69918624 0.36639455 0.83637451]]
after round off[[0.87 0.58 0.28 0.19]
 [0.41 0.12 0.68 0.44]
 [0.56 0.37 0.4  0.11]
 [0.45 0.59 0.16 0.52]
 [0.33 0.7  0.37 0.84]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
np.random.seed(25)
ageArray = np.random.randint(5,15,25)
ageArray.reshape(5,5)




array([[ 9, 11, 12,  7, 13],
       [ 9, 14,  9, 10,  6],
       [12,  8, 13, 12,  8],
       [ 9,  8,  6, 11,  5],
       [14,  5,  7, 10,  9]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
np.random.seed();
length = np.random.randint(1,20,1)
numArray = np.random.randint(5,15,25)
numArray.resize(1,length[0])
numArray

array([[ 7, 12,  7]])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
np.random.seed();
row = np.random.randint(2,8,1)
column = np.random.randint(2,20,1)
floatArray = np.random.rand(5,15,row[0]*column[0])
floatArray.resize(row[0],column[0])
floatArray



array([[0.23882028, 0.48822807, 0.22692821, 0.70464739, 0.25104314,
        0.58523896, 0.62507025],
       [0.75786606, 0.89271168, 0.99748384, 0.80382748, 0.07150617,
        0.10495175, 0.97902639]])

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
np_mat1 = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print('Shape '+str(np_mat1.shape))
print('Type '+str(type(np_mat1)))
print('DType '+str(np_mat1.dtype))


Shape (5, 5)
Type <class 'numpy.ndarray'>
DType int64


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
rowcount = np.array(np_mat1.shape)
rc = np.round(rowcount/2,0)
np_mat1[int(rc[0]),int(rc[1])]

3

#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
np_mat1[2]

array([ 5,  7,  3, 76,  3])

#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
np_mat1[:,3]

array([34, 65, 76, 54,  5])

#### 12. Print the 4 corner pixels of the matrix

In [12]:

rowcount = np.array(np_mat1.shape)
rowMax = rowcount[0]-1 
colMax = rowcount[1]-1 
print(str(np_mat1))
print('top left',str(np_mat1[0,0]))
print('top Right',str(np_mat1[0,rowMax]))
print('bottom left',str(np_mat1[colMax,0]))
print('bottom Right',str(np_mat1[rowMax,colMax]))


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
top left 9
top Right 45
bottom left 23
bottom Right 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
m1 = np_mat1[:2,2:4]
print('m1 = '+str(m1))
m2 = np_mat1[3:5,0:2]
print('m2 = '+str(m2))
m3 = np_mat1[2:5,2:5]
print('m3 = '+str(m3))


m1 = [[50 34]
 [34 65]]
m2 = [[ 7  8]
 [23 12]]
m3 = [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
print('After Reshape') 
print(m1.reshape(1,4))
print(m2.reshape(1,4))
print(m3.reshape(1,9))



After Reshape
[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
print('Vertical'+str(np.concatenate((m1,m2),axis=0)))
print('Horizontal'+str(np.concatenate((m1,m2),axis=1)))



Vertical[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
Horizontal[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
print(m1)
print(m2)
addmatrix = m1+m2
print('Addition'+str(addmatrix))
submatrix = m1-m2
print('Subtraction'+str(submatrix))
submatrix = m1/m2
print('division'+str(submatrix))


[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
Addition[[57 42]
 [57 77]]
Subtraction[[43 26]
 [11 53]]
division[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [18]:
print(m3)
print(m1)
m3[1:,:2] + m1





[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]
[[50 34]
 [34 65]]


array([[56, 88],
       [42, 70]])

#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [17]:
m4 = m1.mean(axis=0)
m4 = m4.reshape(1,2)
m4 = np.concatenate((m1,m4),axis=0)
m4

array([[50. , 34. ],
       [34. , 65. ],
       [42. , 49.5]])

#### 19. Perform the matrix multiplication between m3 and m4

In [19]:
emtMatrix = np.array([[1],[1],[1]])
newm4 = np.concatenate((m4,emtMatrix),axis=1)
m3*newm4.astype(int)


array([[ 150, 2584,    3],
       [ 204, 3510,    6],
       [ 336,  245,    8]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
print('Mean',str(np_mat1.mean(axis=1)))
print('Variance',str(np_mat1.var(axis=1)))
print('Standard Deviation',str(np_mat1.std(axis=1)))


Mean [32.6 27.6 18.8 16.2 11.2]
Variance [214.64 548.24 820.16 357.76  39.76]
Standard Deviation [14.65059726 23.41452541 28.63843571 18.91454467  6.30555311]


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [21]:
runs = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])  
balls = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]]) 
players = np.array(['MSD','Kholi','Rohit','Rahul','Dhawan'])
battingAvg = runs.mean(axis=1)
avgstrRate = runs/balls * 100
strRate = np.round(avgstrRate.mean(axis=1),2)
strRate = strRate.reshape(5,1)
players = players.reshape(5,1)
battingAvg = battingAvg.reshape(5,1)
result = np.concatenate((battingAvg,strRate),axis=1)
print('Sort By Average')
print(np.concatenate((players[result[:,0].argsort()][::-1],result[result[:,0].argsort()][::-1]),axis=1))
print('Sort By StrikeRate')
print(np.concatenate((players[result[:,1].argsort()][::-1],result[result[:,1].argsort()][::-1]),axis=1))

Sort By Average
[['Kholi' '53.5' '81.7']
 ['Rohit' '51.5' '62.18']
 ['MSD' '47.25' '94.91']
 ['Rahul' '29.0' '163.0']
 ['Dhawan' '13.25' '47.96']]
Sort By StrikeRate
[['Rahul' '29.0' '163.0']
 ['MSD' '47.25' '94.91']
 ['Kholi' '53.5' '81.7']
 ['Rohit' '51.5' '62.18']
 ['Dhawan' '13.25' '47.96']]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [22]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
print("Totaly "+str(len(marks[marks<50])) + ' Students FAIL and ' +str(len(marks[marks>50]))+' Students PASS')


Totaly 3 Students FAIL and 7 Students PASS


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [23]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
for index,mark in enumerate(marks):
  if mark > 79 and mark < 95:
    marks[index] = mark+5
  if mark > 44 and mark < 50:
    marks[index] = mark+5  
  if mark > 94:
    marks[index] = 100  
print("Totaly "+str(len(marks[marks<50])) + ' Students FAIL and ' +str(len(marks[marks>50]))+' Students PASS')
print('Marks'+str(marks))

Totaly 1 Students FAIL and 9 Students PASS
Marks[ 65  89  52  56  94 100  53  77  85  39]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [24]:
import time
np.random.seed(100)
x = np.random.randint(1,60000,60000)
y = np.random.randint(1,60000,60000)
timer_list = list([])
for i,j in zip(x,y):
  start_time = time.time()
  (i**2 +8) / j
  timer_list.append(time.time()-start_time)
timer_list

[9.5367431640625e-06,
 2.1457672119140625e-06,
 1.6689300537109375e-06,
 1.1920928955078125e-06,
 1.6689300537109375e-06,
 1.1920928955078125e-06,
 1.1920928955078125e-06,
 1.6689300537109375e-06,
 1.430511474609375e-06,
 1.1920928955078125e-06,
 1.430511474609375e-06,
 1.1920928955078125e-06,
 1.1920928955078125e-06,
 1.6689300537109375e-06,
 1.1920928955078125e-06,
 1.430511474609375e-06,
 1.1920928955078125e-06,
 1.9073486328125e-06,
 1.6689300537109375e-06,
 1.1920928955078125e-06,
 1.430511474609375e-06,
 1.1920928955078125e-06,
 1.1920928955078125e-06,
 9.5367431640625e-07,
 1.1920928955078125e-06,
 9.5367431640625e-07,
 1.430511474609375e-06,
 1.6689300537109375e-06,
 1.1920928955078125e-06,
 1.430511474609375e-06,
 1.430511474609375e-06,
 1.1920928955078125e-06,
 1.430511474609375e-06,
 1.430511474609375e-06,
 1.1920928955078125e-06,
 1.6689300537109375e-06,
 1.1920928955078125e-06,
 1.1920928955078125e-06,
 1.1920928955078125e-06,
 1.1920928955078125e-06,
 1.430511474609375e-0

#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [26]:
print('https://github.com/sachinSamson/NumPy.git')




https://github.com/sachinSamson/NumPy.git
